export const data = [
	'Did you know that ducks have regional accents?',
	'I once met a man who claimed he could talk to mushrooms.',
	'Why does my cat insist on knocking over my plants at 3 AM?',
	'I had a dream where I was a piece of toast. It was oddly comforting.',
	'If you could be any fruit, which would you be and why?',
	'Sometimes I feel like my toaster is judging me.',
	"Why do bananas turn brown so quickly? It's a mystery.",
	'Do you think pigeons ever get tired of city life?',
	"I've been considering learning how to juggle. Thoughts?",
	'Have you ever seen a ghost? I think my house might be haunted by one.',
	'Why do we park on driveways and drive on parkways?',
	"I named my car 'Bessie'. She's a temperamental old lady.",
	'Why does my goldfish always stare at me like it knows something?',
	'If you could swap lives with any fictional character, who would it be?',
	'Have you ever wondered what clouds taste like?',
	"I'm convinced my dog understands every word I say.",
	'Why does the moon look bigger some nights?',
	'I think squirrels are secretly plotting world domination.',
	'I tried to bake a cake yesterday, and it turned out like a brick.',
	'If you could have any superpower, what would it be?',
	'Do you think plants have feelings?',
	'Why is it that whenever I wear white, I spill something on it?',
	'I saw a double rainbow yesterday. It felt magical.',
	"Have you ever had a conversation with a tree? It's surprisingly therapeutic.",
	'Why do socks always go missing in the laundry?',
	'I once found a potato that looked exactly like Elvis.',
	'What if dogs are actually humans in disguise?',
	'I tried to write a novel once, but I got stuck on the first page.',
	'Do you think time travel will ever be possible?',
	'Why does my coffee always go cold so quickly?',
	'I think my plants are plotting to take over my apartment.',
	'If you could live in any time period, which would you choose?',
	'Why do my shoelaces always come untied at the worst moments?',
	'I once saw a cloud that looked like a dragon. It was epic.',
	'Do you think fish ever get bored in their tanks?',
	'I have a theory that birds are actually robots.',
	'Why do I always forget my umbrella on the days it rains?',
	'I tried to learn the ukulele, but my fingers are too clumsy.',
	'If you could have dinner with any historical figure, who would it be?',
	'Why do cats always sit in the most inconvenient places?',
	'I saw a documentary about competitive dog grooming. It was surprisingly intense.',
	'Do you think aliens exist? I bet they do.',
	'Why do my houseplants always look so sad?',
	'I once got lost in a corn maze for three hours.',
	'If you could have any animal as a pet, what would it be?',
	'Why do I always crave chocolate at midnight?',
	'I think my refrigerator is trying to communicate with me.',
	'I once met a man who claimed he could speak fluent dolphin.',
	"Why do my keys always hide when I'm in a hurry?",
	'I saw a cat yesterday that had two different colored eyes.',
	"Do you think we'll ever discover life on other planets?",
	'Why does my coffee maker always break down on Mondays?',
	'I tried to meditate once, but I fell asleep.',
	'If you could only eat one food for the rest of your life, what would it be?',
	'Why do my glasses always smudge right after I clean them?',
	'I think my neighbor is secretly a superhero.',
	'I once found a cloud shaped exactly like a unicorn.',
	'Why do I always lose one sock in the dryer?',
	'If you could have a conversation with any animal, which would it be?',
	'I saw a pigeon wearing a tiny hat yesterday.',
	'Why does my laptop always freeze right before a deadline?',
	'I think my toaster is haunted.',
	'If you could visit any planet, which one would you choose?',
	'Why do I always forget my grocery list at home?',
	'I tried to learn origami, but all I can make are paper wads.',
	"Do you think there's a secret society of squirrels?",
	'Why does my alarm clock always go off at the worst possible moment?',
	'I saw a squirrel yesterday that looked like it was plotting something.',
	'If you could be any mythical creature, which would you be?',
	'Why do my favorite shows always get canceled?',
	'I think my houseplant is trying to communicate with me.',
	'I once met a person who claimed they could speak fluent Klingon.',
	'Why does my phone always die right when I need it most?',
	'I saw a cloud yesterday that looked like a giant turtle.',
	'If you could live in any fictional world, which would it be?',
	'Why do I always spill coffee on my favorite shirt?',
	'I tried to grow tomatoes once, but they all turned out tiny.',
	"Do you think trees have secret lives when we're not looking?",
	'Why do I always misplace my headphones right before a long trip?',
	'I saw a documentary about extreme ironing. It was oddly fascinating.',
	'If you could speak any language fluently, which would it be?',
	'Why does my cat always sit on my keyboard?',
	'I once found a rock that looked exactly like a heart.',
	'If you could have any job in the world, what would it be?',
	'Why do I always get hiccups at the worst times?',
	'I think my vacuum cleaner is secretly alive.',
	'I saw a cloud that looked like a giant fish yesterday.',
	'If you could time travel, where would you go?',
	'Why do I always forget to charge my phone overnight?',
	'I tried to knit a scarf once, but it ended up as a tangled mess.',
	'Do you think there are parallel universes?',
	"Why do I always get stuck in traffic when I'm in a hurry?",
	'I saw a documentary about competitive sheep shearing. It was intense.',
	'If you could have any magical ability, what would it be?',
	'Why do I always lose my pen right when I need it?',
	'I think my microwave is plotting against me.',
	'I saw a pigeon yesterday that seemed to be following me.',
	'If you could live in any country, which would it be?',
	'Why do I always get the hiccups in the middle of important meetings?',
	'I once met a person who could balance a spoon on their nose for hours.',
	'Do you ever wonder if plants can hear us talking?',
	'I saw a turtle yesterday that was missing a leg, but it seemed happy.',
	'Why do I always find things in the last place I look?',
	'If you could be a fly on the wall anywhere, where would it be?',
	'I once saw a dog that could skateboard.',
	'Why do I always forget names right after being introduced?',
	'Do you think jellyfish are aware of their own existence?',
	'I tried to build a birdhouse once, but it ended up as firewood.',
	'If you could live underwater, would you?',
	'Why do I always lose my remote control in the couch cushions?',
	'I saw a lizard doing push-ups yesterday. It was very motivated.',
	'Do you think there are secret passages in every old house?',
	'Why do I always end up with too many tabs open on my browser?',
	'If you could write a letter to your future self, what would you say?',
	"I once met someone who could solve a Rubik's cube in under a minute.",
	'Why do I always get caught in the rain without an umbrella?',
	'Do you think there are more doors or wheels in the world?',
	'I tried to paint a landscape once, but it looked like a mess.',
	'If you could instantly master any skill, what would it be?',
	'Why do I always run out of toothpaste at the worst time?',
	'I saw a cloud yesterday that looked like a giant whale.',
	"Do you think time travel would be more trouble than it's worth?",
	'Why do I always forget to turn off the lights when I leave the house?',
	'If you could be invisible for a day, what would you do?',
	"I tried to learn sign language, but it's harder than it looks.",
	'Do you think dreams have hidden meanings?',
	'Why do I always drop my phone right after getting a new case?',
	'I saw a butterfly with one wing much bigger than the other.',
	'If you could live in any book, which one would it be?',
	'Why do I always spill something right after cleaning up?',
	'I think my car is trying to tell me something with its noises.',
	'I once met someone who could play five instruments at the same time.',
	"Do you think there's a hidden city inside the Earth?",
	'Why do I always get the urge to travel when I have the least time?',
	'I tried to bake cookies, but they came out as one giant cookie.',
	'If you could control the weather, what would you choose?',
	'Why do I always find things in the weirdest places?',
	'I saw a dog yesterday that looked like it was smiling at me.',
	"Do you think animals have their own languages we can't understand?",
	'Why do I always forget to water my plants until they look sad?',
	'I think my computer has a mind of its own.',
	'I once found a seashell shaped like a star.',
	'If you could redesign the human body, what would you change?',
	"Why do I always lose track of time when I'm having fun?",
];

export const sentence = (): string => {
	return data[Math.floor(Math.random() * data.length)];
};

export const sentences = (amount: number): string[] => {
	const result = new Array(amount);
	for (let index = 0; index < amount; index++) {
		result[index] = data[Math.floor(Math.random() * data.length)];
	}
	return result;
};
