export const data = [
	'The Internet is becoming the town square for the global village of tomorrow. - Bill Gates',
	'Stay hungry, stay foolish. - Steve Jobs',
	'Any sufficiently advanced technology is indistinguishable from magic. - Arthur C. Clarke',
	'Life is too short to remove USB safely.',
	"There are 10 types of people in the world: those who understand binary, and those who don't.",
	"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
	'To err is human, but to really foul things up you need a computer.',
	"If at first you don't succeed; call it version 1.0.",
	"Why do Java developers wear glasses? Because they can't C#.",
	'Artificial intelligence is no match for natural stupidity.',
	"The only thing worse than a computer that won't start is a computer that starts blue screening.",
	"I would love to change the world, but they won't give me the source code.",
	'My software never has bugs. It just develops random features.',
	"The cloud is just someone else's computer.",
	'Computers are like air conditioners. They work fine until you start opening windows.',
	'The only problem with troubleshooting is that sometimes trouble shoots back.',
	"If it's not on Google, it doesn't exist.",
	'In a world without fences and walls, who needs Gates and Windows?',
	'Ctrl+Alt+Del is the ultimate power move.',
	'The Internet: where men are men, women are men, and children are FBI agents.',
	"I'm sorry, Dave. I'm afraid I can't do that. - HAL 9000",
	"A user interface is like a joke. If you have to explain it, it's not that good.",
	'Programmers are tools for converting caffeine into code.',
	"There's no place like 127.0.0.1.",
	'First, solve the problem. Then, write the code. - John Johnson',
	'Computers are useless. They can only give you answers. - Pablo Picasso',
	'In God we trust. All others must bring data. - W. Edwards Deming',
	'Technology is best when it brings people together. - Matt Mullenweg',
	'If you think your users are idiots, only idiots will use it. - Linus Torvalds',
	'Innovation distinguishes between a leader and a follower. - Steve Jobs',
	"On the Internet, nobody knows you're a dog.",
	'Talk is cheap. Show me the code. - Linus Torvalds',
	'First, solve the problem. Then, write the code.',
	'The best way to predict the future is to invent it. - Alan Kay',
	'Software is a gas; it expands to fill its container.',
	'A computer once beat me at chess, but it was no match for me at kickboxing.',
	'The computer was born to solve problems that did not exist before. - Bill Gates',
	'Simplicity is the soul of efficiency. - Austin Freeman',
	"Code is like humor. When you have to explain it, it's bad.",
	'Make it work, make it right, make it fast. - Kent Beck',
	'Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson',
	'Good design is good business. - Thomas Watson Jr.',
	'Walking on water and developing software from a specification are easy if both are frozen.',
	'The goal is to turn data into information, and information into insight. - Carly Fiorina',
	'I think it is inevitable that people program poorly. Training will not substantially help matters. - Edsger Dijkstra',
	'The computer is a moron. - Peter Drucker',
	'Computers are good at following instructions, but not at reading your mind.',
	'If debugging is the process of removing software bugs, then programming must be the process of putting them in.',
	'Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates',
	'To iterate is human, to recurse divine. - L. Peter Deutsch',
	"You can't have great software without a great team, and most software teams behave like dysfunctional families. - Jim McCarthy",
	"The trouble with programmers is that you can never tell what a programmer is doing until it's too late.",
	'Weeks of programming can save you hours of planning.',
	'Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program. - Linus Torvalds',
	'The computer does not solve problems; it executes solutions, predetermined by the programmer. - Isaac Asimov',
	'Computers are like Old Testament gods; lots of rules and no mercy. - Joseph Campbell',
	'One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man. - Elbert Hubbard',
	'640K ought to be enough for anybody. - Bill Gates',
	'The more you know, the more you realize you know nothing.',
	'Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning. - Rick Cook',
	"Computers make it easier to do a lot of things, but most of the things they make easier to do don't need to be done. - Andy Rooney",
	'Software and cathedrals are much the same — first we build them, then we pray.',
	'There is an easy way and a hard way. The hard part is finding the easy way.',
	'The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. - Stephen Hawking',
	'We are stuck with technology when what we really want is just stuff that works. - Douglas Adams',
	'The best thing about a boolean is even if you are wrong, you are only off by a bit. - Anonymous',
	'The Internet is the most important single development in the history of human communication since the invention of call waiting. - Dave Barry',
	'Computers are like bikinis. They save people a lot of guesswork. - Sam Ewing',
	'A computer once beat me at chess, but it was no match for me at kickboxing. - Emo Philips',
	'The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time. - Tom Cargill',
	"In theory, theory and practice are the same. In practice, they're not. - Yogi Berra",
	'Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler',
	'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - John Woods',
	'Computers are like a bicycle for our minds. - Steve Jobs',
	'The real problem is not whether machines think but whether men do. - B.F. Skinner',
	"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
	"Never trust a computer you can't throw out a window. - Steve Wozniak",
	'The most technologically efficient machine that man has ever invented is the book. - Northrop Frye',
	'Computers are magnificent tools for the realization of our dreams, but no machine can replace the human spark of spirit, compassion, love, and understanding. - Louis Gerstner',
	"One person's data is another person's noise.",
	"Real knowledge is to know the extent of one's ignorance. - Confucius",
	'Technology is a useful servant but a dangerous master. - Christian Lous Lange',
	'To invent, you need a good imagination and a pile of junk. - Thomas Edison',
	"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code. - Dan Salomon",
	'If you automate a mess, you get an automated mess. - Rod Michael',
	'The human spirit must prevail over technology. - Albert Einstein',
	'The best way to get a project done faster is to start sooner. - Jim Highsmith',
	'There is no reason anyone would want a computer in their home. - Ken Olsen',
	"There's a way to do it better - find it. - Thomas Edison",
	'The most important property of a program is whether it accomplishes the intention of its user. - C.A.R. Hoare',
	"The greatest danger in times of turbulence is not the turbulence; it is to act with yesterday's logic. - Peter Drucker",
	'Any technology distinguishable from magic is insufficiently advanced. - Gregory Benford',
	"It's not a bug - it's an undocumented feature.",
	'Program testing can be a very effective way to show the presence of bugs, but is hopelessly inadequate for showing their absence. - Edsger Dijkstra',
	'Intelligence is the ability to adapt to change. - Stephen Hawking',
	"The advance of technology is based on making it fit in so that you don't really even notice it, so it's part of everyday life. - Bill Gates",
	'Do not trust atoms. They make up everything!',
	'Code never lies, comments sometimes do.',
	'An algorithm is like a recipe.',
	'Programmers are constantly making things more efficient - until they make them unusable.',
	'There is no Ctrl-Z in life.',
	'Without requirements or design, programming is the art of adding bugs to an empty text file. - Louis Srygley',
	'The best performance improvement is the transition from the nonworking state to the working state. - John Ousterhout',
	'It has become appallingly obvious that our technology has exceeded our humanity. - Albert Einstein',
	"If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
	"Technology presumes there's just one right way to do things and there never is. - Robert M. Pirsig",
	'Simplicity is prerequisite for reliability. - Edsger Dijkstra',
	'Most of the good programmers do programming not because they expect to get paid, but because it is fun to program. - Linus Torvalds',
	'No matter how well you know the rules, you must know when to break them.',
	"Be nice to nerds. Chances are you'll end up working for one. - Charles J. Sykes",
	"It's hardware that makes a machine fast. It's software that makes a fast machine slow. - Craig Bruce",
	'Machines take me by surprise with great frequency. - Alan Turing',
	'The function of good software is to make the complex appear to be simple.',
	'Every great developer you know got there by solving problems they were unqualified to solve until they actually did it. - Patrick McKenzie',
	'Code is poetry. - Automattic',
	'Old programmers never die. They just lose their memory.',
	'In code we trust.',
	'The best thing about coding is the debugging process. - said no one ever',
	'When life gives you lemons, write a script to make lemonade.',
	'Keep calm and code on.',
	'The machine does not isolate man from the great problems of nature but plunges him more deeply into them. - Antoine de Saint-Exupéry',
	"Your mind is programmable - if you're not programming your mind, someone else will. - Jeremy Hammond",
	"Code like there's no tomorrow. Tomorrow might be a better day to refactor.",
	'Hello, world!',
	'To understand recursion, you must first understand recursion.',
	'What one programmer can do in one month, two programmers can do in two months. - Fred Brooks',
	'Perfection (in design) is achieved not when there is nothing more to add, but rather when there is nothing more to take away. - Antoine de Saint-Exupéry',
	"You miss 100% of the shots you don't take. - Wayne Gretzky",
	'The purpose of software engineering is to control complexity, not to create it. - Pamela Zave',
	'There are two ways to write error-free programs; only the third one works. - Alan Perlis',
];

export const quote = (): string => {
	return data[Math.floor(Math.random() * data.length)];
};

export const quotes = (amount: number): string[] => {
	const result = new Array(amount);
	for (let index = 0; index < amount; index++) {
		result[index] = data[Math.floor(Math.random() * data.length)];
	}
	return result;
};
