name: check fluxify app

on:
  push:
    branches: [main, develop, feature/*, refactor/*, bugfix/*, hotfix/*]

jobs:
  check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install
        run: bun install

      - name: check
        run: bun check
